define(['hogan'], function(Hogan) {
  var t = {
    /* jshint ignore:start */
    'modal-text' : new Hogan.Template({code: function (c,p,i) { var t=this;t.b(i=i||"");if(t.s(t.f("additionalViewTop",c,p,1),c,p,0,22,84,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("    <div class=\"modal-text-additional-view-container\"></div>");t.b("\n" + i);});c.pop();}t.b("\n" + i);if(t.s(t.f("escapeHtml",c,p,1),c,p,0,123,469,"{{ }}")){t.rs(c,p,function(c,p,t){if(t.s(t.f("paragraph",c,p,1),c,p,0,138,250,"{{ }}")){t.rs(c,p,function(c,p,t){if(t.s(t.f("blocks",c,p,1),c,p,0,150,238,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("<p");if(t.s(t.f("paragraphCssClass",c,p,1),c,p,0,175,205,"{{ }}")){t.rs(c,p,function(c,p,t){t.b(" class=\"");t.b(t.v(t.f("paragraphCssClass",c,p,0)));t.b("\"");});c.pop();}t.b(">");t.b(t.v(t.d(".",c,p,0)));t.b("</p>");t.b("\n" + i);});c.pop();}});c.pop();}if(t.s(t.f("list",c,p,1),c,p,0,274,459,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("<ul");if(t.s(t.f("listCssClass",c,p,1),c,p,0,295,320,"{{ }}")){t.rs(c,p,function(c,p,t){t.b(" class=\"");t.b(t.v(t.f("listCssClass",c,p,0)));t.b("\"");});c.pop();}t.b(">");t.b("\n" + i);if(t.s(t.f("blocks",c,p,1),c,p,0,350,441,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("    <li");if(t.s(t.f("listItemCssClass",c,p,1),c,p,0,379,408,"{{ }}")){t.rs(c,p,function(c,p,t){t.b(" class=\"");t.b(t.v(t.f("listItemCssClass",c,p,0)));t.b("\"");});c.pop();}t.b(">");t.b(t.v(t.d(".",c,p,0)));t.b("</li>");t.b("\n" + i);});c.pop();}t.b("</ul>");t.b("\n" + i);});c.pop();}});c.pop();}t.b("\n" + i);if(!t.s(t.f("escapeHtml",c,p,1),c,p,1,0,0,"")){if(t.s(t.f("paragraph",c,p,1),c,p,0,516,646,"{{ }}")){t.rs(c,p,function(c,p,t){if(t.s(t.f("blocks",c,p,1),c,p,0,532,634,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("        <p");if(t.s(t.f("paragraphCssClass",c,p,1),c,p,0,565,595,"{{ }}")){t.rs(c,p,function(c,p,t){t.b(" class=\"");t.b(t.v(t.f("paragraphCssClass",c,p,0)));t.b("\"");});c.pop();}t.b(">");t.b(t.t(t.d(".",c,p,0)));t.b("</p>");t.b("\n" + i);});c.pop();}});c.pop();}t.b("\n" + i);if(t.s(t.f("list",c,p,1),c,p,0,671,890,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("    <ul");if(t.s(t.f("listCssClass",c,p,1),c,p,0,696,721,"{{ }}")){t.rs(c,p,function(c,p,t){t.b(" class=\"");t.b(t.v(t.f("listCssClass",c,p,0)));t.b("\"");});c.pop();}t.b(">");t.b("\n" + i);if(t.s(t.f("blocks",c,p,1),c,p,0,759,868,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("            <li");if(t.s(t.f("listItemCssClass",c,p,1),c,p,0,796,825,"{{ }}")){t.rs(c,p,function(c,p,t){t.b(" class=\"");t.b(t.v(t.f("listItemCssClass",c,p,0)));t.b("\"");});c.pop();}t.b(">");t.b(t.t(t.d(".",c,p,0)));t.b("</li>");t.b("\n" + i);});c.pop();}t.b("    </ul>");t.b("\n" + i);});c.pop();}};t.b("\n" + i);if(t.s(t.f("additionalViewBottom",c,p,1),c,p,0,942,1000,"{{ }}")){t.rs(c,p,function(c,p,t){t.b("<div class=\"modal-text-additional-view-container\"></div>");t.b("\n" + i);});c.pop();}return t.fl(); },partials: {}, subs: {  }})
    /* jshint ignore:end */
  },
  r = function(n) {
    var tn = t[n];
    return function(c, p, i) {
      return tn.render(c, p || t, i);
    };
  };
  return {
    'modal-text' : r('modal-text')
  };
});